title: BY Github PLP
description: The Blue Yonder way to GitHub mastery
steps:
  - title: 'GitHub Actions: Continuous Integration'
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
    link: >-
      https://lab.github.com/githubtraining/github-actions:-continuous-integration
    course: 'https://lab.github.com/githubtraining'
    description: >-
      GitHub Actions makes it easier than ever to incorporate continuous
      integration (CI) into your repositories.​This course will get you from
      zero-to-CI by setting up two workflow files to automate the way you work.
  - title: 'GitHub Actions: Using GitHub Script'
  - title: 'GitHub Actions: Write Docker container actions'
    link: >-
      https://lab.github.com/githubtraining/github-actions:-write-docker-container-actions
    description: >-
      Learn how to write your own GitHub Docker container action! This course
      will empower you to begin automating customized tasks unique to your
      workflow.
    course: 'https://lab.github.com/githubtraining'
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
    link: 'GitHub Actions: Using GitHub Script'
    course: 'https://lab.github.com/githubtraining'
    description: >-
      GitHub Script is a special action that allows using octokit/rest.js
      directly in a workflow file.  Over the duration of this course you will
      learn the skills needed to begin using the GitHub Script action to
      interact with your repository which will save you from creating full blown
      actions that carry unnecessary overhead.
  - title: 'GitHub Actions: Writing JavaScript Actions'
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
    description: >-
      GitHub Actions makes it easier than ever to incorporate continuous
      integration (CI) into your repositories.​This course will get you from
      zero-to-CI by setting up two workflow files to automate the way you work.
    link: >-
      https://lab.github.com/githubtraining/github-actions:-continuous-integration
    course: 'https://lab.github.com/githubtraining'
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
